### ISSUE TITLE
Migration docs

### ISSUE THREAD

**Issue by pablichjenkov** [MercuryTechnologies/sqkon#2]
Is it possible to add a session in the documentation about how migration works. What would happen if a model schema changes. Perhaps no migration is needed, in such a case how the scenario above is handled, similar to a nosql db?
Would be nice having all these documented.

**Comment by pablichjenkov** [comment]
I see what you describe makes a lot of sense. If I may suggest. I would like an API that allows to specify the migration either by annotation or when defining the Entity itself.
The main problem I face is contributors change the entity fields and forget to update the migration file.
So it may help if the same file where the entity is defined would also have the migration defined.
Although what you describe sounds even better. An API that allows you to specify the serializer.

**Comment by chrisjenx** [comment]
For an API on your entity that would be out of scope, the TLDR is there is no "migration" in the traditional sense, as it just serializes and deserializes your entities, out of the box for now, we'd handle what happens when deserialization fails and "what to do"

Regarding the underlying Sqldelight implementation, it will auto migrate for you if we added any other fields. But I don't thing we would need anything for a while until we expand functionality

**Comment by pablichjenkov** [comment]
Fair enough 👍
